package ventanas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Ejercicio 3.
 *
 * Crear un programa que capture dos números y que muestre cual de los dos es el
 * mayor.
 *
 * @author Hernández
 */
public class Ejercicio03 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio03
     */
    public Ejercicio03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        PanelPrimerNumero = new javax.swing.JPanel();
        txtPrimerNumero = new javax.swing.JTextField();
        PanelSegundoNumero = new javax.swing.JPanel();
        txtSegundoNumero = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JPanel();
        btnLimpiarLabel = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JPanel();
        btnCalcularLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Número mayor");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setText("Primer Número:");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Segundo Número:");

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("¿Cuál es el número mayor ?");

        jLabelResultado.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabelResultado.setForeground(new java.awt.Color(51, 51, 51));
        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PanelPrimerNumero.setBackground(new java.awt.Color(226, 226, 226));

        txtPrimerNumero.setBackground(new java.awt.Color(226, 226, 226));
        txtPrimerNumero.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        txtPrimerNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 226, 226)));

        javax.swing.GroupLayout PanelPrimerNumeroLayout = new javax.swing.GroupLayout(PanelPrimerNumero);
        PanelPrimerNumero.setLayout(PanelPrimerNumeroLayout);
        PanelPrimerNumeroLayout.setHorizontalGroup(
            PanelPrimerNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrimerNumeroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelPrimerNumeroLayout.setVerticalGroup(
            PanelPrimerNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrimerNumeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelSegundoNumero.setBackground(new java.awt.Color(226, 226, 226));

        txtSegundoNumero.setBackground(new java.awt.Color(226, 226, 226));
        txtSegundoNumero.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        txtSegundoNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 226, 226)));

        javax.swing.GroupLayout PanelSegundoNumeroLayout = new javax.swing.GroupLayout(PanelSegundoNumero);
        PanelSegundoNumero.setLayout(PanelSegundoNumeroLayout);
        PanelSegundoNumeroLayout.setHorizontalGroup(
            PanelSegundoNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSegundoNumeroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelSegundoNumeroLayout.setVerticalGroup(
            PanelSegundoNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSegundoNumeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpiar.setBackground(new java.awt.Color(248, 104, 104));

        btnLimpiarLabel.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnLimpiarLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiarLabel.setText("Limpiar");
        btnLimpiarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnCalcular.setBackground(new java.awt.Color(29, 192, 110));

        btnCalcularLabel.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnCalcularLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCalcularLabel.setText("Calcular");
        btnCalcularLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcularLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCalcularLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCalcularLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCalcularLayout = new javax.swing.GroupLayout(btnCalcular);
        btnCalcular.setLayout(btnCalcularLayout);
        btnCalcularLayout.setHorizontalGroup(
            btnCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalcularLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnCalcularLayout.setVerticalGroup(
            btnCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalcularLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(PanelSegundoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrimerNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(PanelPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(PanelSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Limpiar() {
        txtPrimerNumero.setText("");
        txtSegundoNumero.setText("");
    }

    private void btnLimpiarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarLabelMouseClicked
        jLabelResultado.setText("");
        Limpiar();
    }//GEN-LAST:event_btnLimpiarLabelMouseClicked

    private void btnLimpiarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarLabelMouseEntered
        btnLimpiar.setBackground(new Color(233, 78, 78));
    }//GEN-LAST:event_btnLimpiarLabelMouseEntered

    private void btnLimpiarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarLabelMouseExited
        btnLimpiar.setBackground(new Color(248, 104, 104));
    }//GEN-LAST:event_btnLimpiarLabelMouseExited

    private void btnCalcularLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularLabelMouseClicked
        if (txtPrimerNumero.getText().trim().isEmpty() || txtSegundoNumero.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Campos vacios!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            double primerNumero = Double.parseDouble(txtPrimerNumero.getText());
            double segundoNumero = Double.parseDouble(txtSegundoNumero.getText());

            if (primerNumero > segundoNumero) {
                jLabelResultado.setText(primerNumero + " es el número mayor");
            } else if (segundoNumero > primerNumero) {
                jLabelResultado.setText(segundoNumero + " es el número mayor");
            } else {
                jLabelResultado.setText(primerNumero + " es igual a " + segundoNumero);
            }
            Limpiar();
        }
    }//GEN-LAST:event_btnCalcularLabelMouseClicked

    private void btnCalcularLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularLabelMouseEntered
        btnCalcular.setBackground(new Color(26, 162, 94));
    }//GEN-LAST:event_btnCalcularLabelMouseEntered

    private void btnCalcularLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularLabelMouseExited
        btnCalcular.setBackground(new Color(29, 192, 110));
    }//GEN-LAST:event_btnCalcularLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrimerNumero;
    private javax.swing.JPanel PanelSegundoNumero;
    private javax.swing.JPanel btnCalcular;
    private javax.swing.JLabel btnCalcularLabel;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JLabel btnLimpiarLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPrimerNumero;
    private javax.swing.JTextField txtSegundoNumero;
    // End of variables declaration//GEN-END:variables
}
