package ventanas;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 * Ejercicio 4.
 *
 * Elabora un programa que capture el numero de dolares, (investigar a como esta
 * el bitcoin y ponerlo como constante) y que los convierta a bitcoins.
 *
 * https://www.xe.com/es/currencyconverter/convert/?Amount=1&From=USD&To=BTC
 *
 * @author Hernández
 */
public class Ejercicio04 extends javax.swing.JFrame {

    private final double valorBitcoin = 0.0000617403;

    /**
     * Creates new form Ejercicio04
     */
    public Ejercicio04() {
        initComponents();
        jLabelValor.setText("1 USD = " + EliminarNotacionCientifica(valorBitcoin));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        PanelDolares = new javax.swing.JPanel();
        txtDolares = new javax.swing.JTextField();
        PanelBitcoin = new javax.swing.JPanel();
        jLabelResultado = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JPanel();
        btnCalcularLabel = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        btnLimpiarLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USD/BTC");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 17)); // NOI18N
        jLabel1.setText("USD/BTC");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Dólar");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setText("Bitcoin");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setText("=");

        jLabelValor.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(102, 102, 102));

        PanelDolares.setBackground(new java.awt.Color(226, 226, 226));

        txtDolares.setBackground(new java.awt.Color(226, 226, 226));
        txtDolares.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N
        txtDolares.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 226, 226)));

        javax.swing.GroupLayout PanelDolaresLayout = new javax.swing.GroupLayout(PanelDolares);
        PanelDolares.setLayout(PanelDolaresLayout);
        PanelDolaresLayout.setHorizontalGroup(
            PanelDolaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDolaresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        PanelDolaresLayout.setVerticalGroup(
            PanelDolaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDolaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDolares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBitcoin.setBackground(new java.awt.Color(226, 226, 226));

        jLabelResultado.setFont(new java.awt.Font("Roboto Light", 0, 13)); // NOI18N

        javax.swing.GroupLayout PanelBitcoinLayout = new javax.swing.GroupLayout(PanelBitcoin);
        PanelBitcoin.setLayout(PanelBitcoinLayout);
        PanelBitcoinLayout.setHorizontalGroup(
            PanelBitcoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBitcoinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelBitcoinLayout.setVerticalGroup(
            PanelBitcoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBitcoinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCalcular.setBackground(new java.awt.Color(29, 192, 110));

        btnCalcularLabel.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnCalcularLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCalcularLabel.setText("Calcular");
        btnCalcularLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcularLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCalcularLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCalcularLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCalcularLayout = new javax.swing.GroupLayout(btnCalcular);
        btnCalcular.setLayout(btnCalcularLayout);
        btnCalcularLayout.setHorizontalGroup(
            btnCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalcularLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnCalcularLayout.setVerticalGroup(
            btnCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCalcularLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        btnLimpiar.setBackground(new java.awt.Color(248, 104, 104));

        btnLimpiarLabel.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btnLimpiarLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLimpiarLabel.setText("Limpiar");
        btnLimpiarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLabel2)
                            .addGap(176, 176, 176)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(PanelDolares, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel4)
                            .addGap(12, 12, 12)
                            .addComponent(PanelBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDolares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(PanelBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static String EliminarNotacionCientifica(double Número) {
        return new DecimalFormat("#.####################################").format(Número);
    }

    private void btnCalcularLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularLabelMouseClicked
        if (txtDolares.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Campo vacio!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            double dolares = Double.parseDouble(txtDolares.getText());

            double resultado = dolares * valorBitcoin;

            jLabelResultado.setText(EliminarNotacionCientifica(resultado));
        }
    }//GEN-LAST:event_btnCalcularLabelMouseClicked

    private void btnCalcularLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularLabelMouseEntered
        btnCalcular.setBackground(new Color(26, 162, 94));
    }//GEN-LAST:event_btnCalcularLabelMouseEntered

    private void btnCalcularLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularLabelMouseExited
        btnCalcular.setBackground(new Color(29, 192, 110));
    }//GEN-LAST:event_btnCalcularLabelMouseExited

    private void btnLimpiarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarLabelMouseClicked
        txtDolares.setText("");
        jLabelResultado.setText("");
    }//GEN-LAST:event_btnLimpiarLabelMouseClicked

    private void btnLimpiarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarLabelMouseEntered
        btnLimpiar.setBackground(new Color(233, 78, 78));
    }//GEN-LAST:event_btnLimpiarLabelMouseEntered

    private void btnLimpiarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarLabelMouseExited
        btnLimpiar.setBackground(new Color(248, 104, 104));
    }//GEN-LAST:event_btnLimpiarLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBitcoin;
    private javax.swing.JPanel PanelDolares;
    private javax.swing.JPanel btnCalcular;
    private javax.swing.JLabel btnCalcularLabel;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JLabel btnLimpiarLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDolares;
    // End of variables declaration//GEN-END:variables
}
